site_name: Murphy-LeetCode
docs_dir: docs/
repo_name: 'murphyhoucn/Murphy-LeetCode'
repo_url: https://github.com/murphyhoucn/Murphy-LeetCode
theme:
  logo: https://murphyimg.oss-cn-beijing.aliyuncs.com/img/202505311432608.png
  favicon: https://murphyimg.oss-cn-beijing.aliyuncs.com/img/202505311432608.png
  name: material
  language: zh
  static_templates:
    - 404.html
  include_search_page: false
  search_index_only: true
  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate
  palette:
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: deep blue
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: cyan
      accent: deep blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
extra:
  homepage: https://cosmicdusty.cc/
plugins:
  - tags
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

nav:
  - MkDocs: 'MkDocs.md'
  - README: 'README.md'
  - 0001 两数之和: 'CPP/0001.md'
  - 0009 回文数: 'CPP/0009.md'
  - 0013 罗马数字转整数: 'CPP/0013.md'
  - 0014 最长公共前缀: 'CPP/0014.md'
  - 0020 有效的括号: 'CPP/0020.md'
  - 0027 移除元素: 'CPP/0027.md'
  - 0028 找出字符串中第一个匹配项的下标: 'CPP/0028.md'
  - 0035 搜索插入位置: 'CPP/0035.md'
  - 0058 最后一个单词的长度: 'CPP/0058.md'
  - 0066 加一: 'CPP/0066.md'
  - 0067 二进制求和: 'CPP/0067.md'
  - 0069 x的平方根: 'CPP/0069.md'
  - 0070 爬楼梯: 'CPP/0070.md'
  - 0088 合并两个有序数组: 'CPP/0088.md'
  - 0628 三个数的最大乘积: 'CPP/0628.md'
