site_name: Murphy-LeetCode
docs_dir: docs/
repo_name: 'murphyhoucn/Murphy-LeetCode'
repo_url: https://github.com/murphyhoucn/Murphy-LeetCode
theme:
  logo: https://murhyimgur.oss-cn-beijing.aliyuncs.com/website/星星.png
  favicon: https://murhyimgur.oss-cn-beijing.aliyuncs.com/website/星星.png
  name: material
  language: zh
  static_templates:
    - 404.html
  include_search_page: false
  search_index_only: true
  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate
  palette:
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: deep blue
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: cyan
      accent: deep blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
extra:
  homepage: https://cosmicdusty.cc/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

nav:
  - learn: 'index.md'
  - learn: 'index.md'